Minor code changes based on SPERR v0.7.1
robertu94/libpressio-sperr pull request #2
Opened 2023-10-19 20:48 UTC by shaomeng

This PR makes minor code changes based on SPERR v0.7.1

2023-10-24 19:57 UTC, robertu94 requested changes
This is also blocked on NCAR/SPERR#221 being resolved.

2023-10-24 19:57 UTC, robertu94 commented on src/libpressio-sperr.cc
> +                           inc_header_2d, &bitstream, &stream_len);
I think this should be `inc_header` (at least when I tried to build with this PR)

2023-10-24 20:18 UTC, shaomeng commented on src/libpressio-sperr.cc
> +                           inc_header_2d, &bitstream, &stream_len);
Correct. Already fixed.

2023-10-25 15:00 UTC, robertu94 approved these changes

2023-10-25 15:03 UTC, merged